### ISSUE TITLE
[bug] .test.ts file name pattern is not supported

### ISSUE THREAD

**Issue by wizzard0** [johtela/litscript#13] opened 2021-11-06 14:25 UTC
I believe this is a separate issue from #12, and it's a bug, because .test.ts files don't contain JSX markup and should be picked up fine with regular TypeScript parser.

Expected Behaviour:
- `.test.ts` files are compiled as regular typescript

Observed Behaviour:
- Translator not registered for file `index.test.ts`

Steps to reproduce:
- See #12 , then add `index.test.ts` file

**Comment by johtela** [comment] 2022-02-18 17:59
Duplicate of #12

**Closed as completed by johtela** 2022-02-18 17:59 UTC
